//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Common_cmd_Cancel {
            get {
                return ResourceManager.GetString("Common_cmd_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Less.
        /// </summary>
        internal static string Common_cmd_Less {
            get {
                return ResourceManager.GetString("Common_cmd_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More.
        /// </summary>
        internal static string Common_cmd_More {
            get {
                return ResourceManager.GetString("Common_cmd_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string Common_cmd_No {
            get {
                return ResourceManager.GetString("Common_cmd_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string Common_cmd_OK {
            get {
                return ResourceManager.GetString("Common_cmd_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Common_cmd_Save {
            get {
                return ResourceManager.GetString("Common_cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Common_cmd_Yes {
            get {
                return ResourceManager.GetString("Common_cmd_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Connection_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Connection_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Error_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Error_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Exclamation_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Exclamation_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Forbidden_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Forbidden_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Help_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Help_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Information_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Information_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Locked_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Locked_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Question_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Question_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Search_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Search_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBox_img_Waiting_png {
            get {
                object obj = ResourceManager.GetObject("DialogBox_img_Waiting_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to cancel?.
        /// </summary>
        internal static string DialogBoxProgress_dialog_ConfirmCancel {
            get {
                return ResourceManager.GetString("DialogBoxProgress_dialog_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait....
        /// </summary>
        internal static string DialogBoxProgress_dialog_DefaultMessage {
            get {
                return ResourceManager.GetString("DialogBoxProgress_dialog_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process complete!.
        /// </summary>
        internal static string DialogBoxProgress_dialog_DefaultMessageWhenFinished {
            get {
                return ResourceManager.GetString("DialogBoxProgress_dialog_DefaultMessageWhenFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred:.
        /// </summary>
        internal static string ErrorHandler_dialog_ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorHandler_dialog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error message.
        /// </summary>
        internal static string ErrorHandler_dialog_Subtitle {
            get {
                return ResourceManager.GetString("ErrorHandler_dialog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to deserialize..
        /// </summary>
        internal static string FilesAndStreams_errorMsg_UnableToDeserialize {
            get {
                return ResourceManager.GetString("FilesAndStreams_errorMsg_UnableToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable to read the file:.
        /// </summary>
        internal static string FilesAndStreams_errorMsg_UnableToReadFile {
            get {
                return ResourceManager.GetString("FilesAndStreams_errorMsg_UnableToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to serialize..
        /// </summary>
        internal static string FilesAndStreams_errorMsg_UnableToSerialize {
            get {
                return ResourceManager.GetString("FilesAndStreams_errorMsg_UnableToSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable to write the file:.
        /// </summary>
        internal static string FilesAndStreams_errorMsg_UnableToWriteFile {
            get {
                return ResourceManager.GetString("FilesAndStreams_errorMsg_UnableToWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frmBaseForm_img_TitleBar_jpg {
            get {
                object obj = ResourceManager.GetObject("frmBaseForm_img_TitleBar_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
