//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.ExdControls {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.ExdControls.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No name.
        /// </summary>
        internal static string Album_defaultMsg_NoName {
            get {
                return ResourceManager.GetString("Album_defaultMsg_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change album properties:.
        /// </summary>
        internal static string Album_dialog_AlbumProperties {
            get {
                return ResourceManager.GetString("Album_dialog_AlbumProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caption:.
        /// </summary>
        internal static string Album_dialog_AlbumProperties_Caption {
            get {
                return ResourceManager.GetString("Album_dialog_AlbumProperties_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show names:.
        /// </summary>
        internal static string Album_dialog_AlbumProperties_ShowNames {
            get {
                return ResourceManager.GetString("Album_dialog_AlbumProperties_ShowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thumbnails size:.
        /// </summary>
        internal static string Album_dialog_AlbumProperties_ThumbSize {
            get {
                return ResourceManager.GetString("Album_dialog_AlbumProperties_ThumbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More than one picture are selected: Are you sure you want to continue?.
        /// </summary>
        internal static string Album_dialog_ConfirmModifiyPropertiesForSeveralPictures {
            get {
                return ResourceManager.GetString("Album_dialog_ConfirmModifiyPropertiesForSeveralPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete all pictures ?.
        /// </summary>
        internal static string Album_dialog_DeleteAllPictures {
            get {
                return ResourceManager.GetString("Album_dialog_DeleteAllPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this picture ?.
        /// </summary>
        internal static string Album_dialog_DeleteSelectedPictures {
            get {
                return ResourceManager.GetString("Album_dialog_DeleteSelectedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caption:.
        /// </summary>
        internal static string Album_dialog_PictureProperties_Caption {
            get {
                return ResourceManager.GetString("Album_dialog_PictureProperties_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filename:.
        /// </summary>
        internal static string Album_dialog_PictureProperties_Filename {
            get {
                return ResourceManager.GetString("Album_dialog_PictureProperties_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format:.
        /// </summary>
        internal static string Album_dialog_PictureProperties_Format {
            get {
                return ResourceManager.GetString("Album_dialog_PictureProperties_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name:.
        /// </summary>
        internal static string Album_dialog_PictureProperties_Name {
            get {
                return ResourceManager.GetString("Album_dialog_PictureProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size:.
        /// </summary>
        internal static string Album_dialog_PictureProperties_Size {
            get {
                return ResourceManager.GetString("Album_dialog_PictureProperties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change selected pictures properties:.
        /// </summary>
        internal static string Album_dialog_SelectedPicturesProperties {
            get {
                return ResourceManager.GetString("Album_dialog_SelectedPicturesProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change selected pictures properties (red text boxes will not be modified, to toggle between red and white, double click on the text box):.
        /// </summary>
        internal static string Album_dialog_SelectedPicturesProperties_SeveralPictures {
            get {
                return ResourceManager.GetString("Album_dialog_SelectedPicturesProperties_SeveralPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when opening {0}..
        /// </summary>
        internal static string Album_errorMsg_ErrorWhenOpeningPicture {
            get {
                return ResourceManager.GetString("Album_errorMsg_ErrorWhenOpeningPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add pictures....
        /// </summary>
        internal static string Album_menu_AddPictures {
            get {
                return ResourceManager.GetString("Album_menu_AddPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Album properties....
        /// </summary>
        internal static string Album_menu_AlbumProperties {
            get {
                return ResourceManager.GetString("Album_menu_AlbumProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back color....
        /// </summary>
        internal static string Album_menu_ChangeBackColor {
            get {
                return ResourceManager.GetString("Album_menu_ChangeBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change colors.
        /// </summary>
        internal static string Album_menu_ChangeColors {
            get {
                return ResourceManager.GetString("Album_menu_ChangeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fore color....
        /// </summary>
        internal static string Album_menu_ChangeForeColor {
            get {
                return ResourceManager.GetString("Album_menu_ChangeForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert and save (ask for each picture)....
        /// </summary>
        internal static string Album_menu_ConvertAndSaveSelectedPictures {
            get {
                return ResourceManager.GetString("Album_menu_ConvertAndSaveSelectedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete all pictures.
        /// </summary>
        internal static string Album_menu_DeleteAllPictures {
            get {
                return ResourceManager.GetString("Album_menu_DeleteAllPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected pictures.
        /// </summary>
        internal static string Album_menu_DeleteSelectedPictures {
            get {
                return ResourceManager.GetString("Album_menu_DeleteSelectedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Using existing formats and names....
        /// </summary>
        internal static string Album_menu_SavePicturesUsingExistingNames {
            get {
                return ResourceManager.GetString("Album_menu_SavePicturesUsingExistingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsing new format and names....
        /// </summary>
        internal static string Album_menu_SavePicturesUsingNewNames {
            get {
                return ResourceManager.GetString("Album_menu_SavePicturesUsingNewNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save selected pictures.
        /// </summary>
        internal static string Album_menu_SaveSelectedPictures {
            get {
                return ResourceManager.GetString("Album_menu_SaveSelectedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected pictures properties.
        /// </summary>
        internal static string Album_menu_SelectedPicturesProperties {
            get {
                return ResourceManager.GetString("Album_menu_SelectedPicturesProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show names.
        /// </summary>
        internal static string Album_menu_ShowNames {
            get {
                return ResourceManager.GetString("Album_menu_ShowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom....
        /// </summary>
        internal static string Album_menu_Zoom {
            get {
                return ResourceManager.GetString("Album_menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (No picture properties).
        /// </summary>
        internal static string Album_NoPictureProperties {
            get {
                return ResourceManager.GetString("Album_NoPictureProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string AltIconToForm_menu_Exit {
            get {
                return ResourceManager.GetString("AltIconToForm_menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show.
        /// </summary>
        internal static string AltIconToForm_menu_Show {
            get {
                return ResourceManager.GetString("AltIconToForm_menu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjusted size.
        /// </summary>
        internal static string DialogBoxPictureZoom_FormText_AdjustedSizeMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_FormText_AdjustedSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real size mode.
        /// </summary>
        internal static string DialogBoxPictureZoom_FormText_RealSizeMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_FormText_RealSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom mode.
        /// </summary>
        internal static string DialogBoxPictureZoom_FormText_ZoomMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_FormText_ZoomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ALL MODES:\*\*→/↓: Next picture\*←/↑: Previous picture\*R-Click: Context menu\*Ctrl+L-Click: Toggle between Zoom and Real size mode\*F1: Help\*Escape: Hide\*\*REAL SIZE MODE:\*\*Ctrl+E: Adjusted size mode\*Mouse wheel: Vertical scroll\*Ctrl+Mouse wheel: Horizontal scroll\*Drag and drop: Change picture position\*Alt+→/↓/←/↑: Change zoom (big increment)\*Ctrl+Alt+→/↓/←/↑: Change zoom (little increment)\*Alt+Mouse wheel: Change zoom (big increment)\*Ctrl+Alt+Mouse wheel: Change zoom (little increment)\*\*ZOOM  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string DialogBoxPictureZoom_Help {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjusted size mode.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_AdjustedSizeMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_AdjustedSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjust zoom to width.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_AdjustToWidth {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_AdjustToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back color.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColor {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Black.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorBlack {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change user color.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorChangeUserColor {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorChangeUserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control color.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorControlColor {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorControlColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark gray.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorDarkGray {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorDarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Program color.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorProgramColor {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorProgramColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User color.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorUserColor {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorUserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à White.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_BackColorWhite {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_BackColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom zoom.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_CustomZoom {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_CustomZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Hide {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next picture.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_NextPicture {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_NextPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other commands.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_OtherCommands {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_OtherCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous picture.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_PreviousPicture {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_PreviousPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real size mode.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_RealSizeMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_RealSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Rotate {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 180°.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Rotate180 {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 90° clockwise.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Rotate90ClockWise {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Rotate90ClockWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 90° counterclockwise.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Rotate90CounterClockWise {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Rotate90CounterClockWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_RotateNone {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_RotateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/Hide color description.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_ShowColorDescription {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_ShowColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_Zoom {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom zoom....
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_ZoomCustom {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_ZoomCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom mode.
        /// </summary>
        internal static string DialogBoxPictureZoom_menu_ZoomMode {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_menu_ZoomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press F1 to see help and shortcuts....
        /// </summary>
        internal static string DialogBoxPictureZoom_ToolTipHelp {
            get {
                return ResourceManager.GetString("DialogBoxPictureZoom_ToolTipHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete {0} item(s)?.
        /// </summary>
        internal static string ExdListView_dialog_DeleteItem {
            get {
                return ResourceManager.GetString("ExdListView_dialog_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this document?.
        /// </summary>
        internal static string ExdTreeView_dialog_DeleteDocument {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this folder?.
        /// </summary>
        internal static string ExdTreeView_dialog_DeleteFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The document already exists in this folder!.
        /// </summary>
        internal static string ExdTreeView_dialog_DocumentAlreadyInFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_DocumentAlreadyInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name for the new folder:.
        /// </summary>
        internal static string ExdTreeView_dialog_NewFolder_Message {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_NewFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name:.
        /// </summary>
        internal static string ExdTreeView_dialog_NewFolder_TextField {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_NewFolder_TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of the folder:.
        /// </summary>
        internal static string ExdTreeView_dialog_NewFolder_TypeField {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_NewFolder_TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name for the selected folder:.
        /// </summary>
        internal static string ExdTreeView_dialog_RenameFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_dialog_RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete document.
        /// </summary>
        internal static string ExdTreeView_menu_DeleteDocument {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete folder.
        /// </summary>
        internal static string ExdTreeView_menu_DeleteFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New root folder....
        /// </summary>
        internal static string ExdTreeView_menu_NewRootFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_NewRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New sibling folder....
        /// </summary>
        internal static string ExdTreeView_menu_NewSiblingFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_NewSiblingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New subfolder....
        /// </summary>
        internal static string ExdTreeView_menu_NewSubfolder {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_NewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename folder....
        /// </summary>
        internal static string ExdTreeView_menu_RenameFolder {
            get {
                return ResourceManager.GetString("ExdTreeView_menu_RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigator_img_Back_png_little {
            get {
                object obj = ResourceManager.GetObject("Navigator_img_Back_png_little", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigator_img_Forward_png_little {
            get {
                object obj = ResourceManager.GetObject("Navigator_img_Forward_png_little", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigator_img_Go_png_little {
            get {
                object obj = ResourceManager.GetObject("Navigator_img_Go_png_little", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigator_img_Home_png_little {
            get {
                object obj = ResourceManager.GetObject("Navigator_img_Home_png_little", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigator_img_Refresh_png_little {
            get {
                object obj = ResourceManager.GetObject("Navigator_img_Refresh_png_little", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Bold_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Bold_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Center_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Center_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Italic_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Italic_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Left_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Left_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Open_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Open_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Right_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Right_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Save_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Save_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextEditor_img_Underline_png {
            get {
                object obj = ResourceManager.GetObject("TextEditor_img_Underline_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
